apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: aplicativo-capacity-db
  namespace: prod-aplicativo-capacity
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aplicativo-capacity-db
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
