[tool.ruff]
ignore = ["E501"]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]

[tool.ruff.pydocstyle]
convention = "google"

[tool.isort]
line_length = 88
multi_line_output = 3
include_trailing_comma = true

[tool.pytest.ini_options]
addopts = "-p no:warnings --ignore=tests/load_test.py"
asyncio_mode = "auto"
log_cli = 1
log_cli_level = "INFO"

[tool.mypy]
disable_error_code = "func-returns-value"
namespace_packages = true
