-- MySQL Script generated by MySQL Workbench
-- Wed Oct 11 13:00:30 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pihu1
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pruebahu1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `espacios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `espacios` ;

CREATE TABLE IF NOT EXISTS `espacios` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `modalidadescontractuales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modalidadescontractuales` ;

CREATE TABLE IF NOT EXISTS `modalidadescontractuales` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `responsabilidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `responsabilidades` ;

CREATE TABLE IF NOT EXISTS `responsabilidades` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(255) NULL DEFAULT NULL,
  `Descripcion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `responsabilidadespormodalidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `responsabilidadespormodalidades` ;

CREATE TABLE IF NOT EXISTS `responsabilidadespormodalidades` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Aplica` TINYINT(1) NULL DEFAULT NULL,
  `Responsabilidad_ID` INT NULL DEFAULT NULL,
  `Modalidad_ID` INT NULL DEFAULT NULL,
  `Espacio_ID` INT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `responsabilidadespormodalidades_ibfk_1`
    FOREIGN KEY (`Responsabilidad_ID`)
    REFERENCES `responsabilidades` (`ID`),
  CONSTRAINT `responsabilidadespormodalidades_ibfk_2`
    FOREIGN KEY (`Modalidad_ID`)
    REFERENCES `modalidadescontractuales` (`ID`),
  CONSTRAINT `responsabilidadespormodalidades_ibfk_3`
    FOREIGN KEY (`Espacio_ID`)
    REFERENCES `espacios` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `Responsabilidad_ID` ON `responsabilidadespormodalidades` (`Responsabilidad_ID` ASC) VISIBLE;

CREATE INDEX `Modalidad_ID` ON `responsabilidadespormodalidades` (`Modalidad_ID` ASC) VISIBLE;

CREATE INDEX `Espacio_ID` ON `responsabilidadespormodalidades` (`Espacio_ID` ASC) INVISIBLE;


-- -----------------------------------------------------
-- Table `espacio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `espacio` ;

CREATE TABLE IF NOT EXISTS `espacio` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `modalidadcontractual`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modalidadcontractual` ;

CREATE TABLE IF NOT EXISTS `modalidadcontractual` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `evento` ;

CREATE TABLE IF NOT EXISTS `evento` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(255) NOT NULL,
  `ModalidadContractualID` INT NULL DEFAULT NULL,
  `EspacioID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `evento_ibfk_1`
    FOREIGN KEY (`ModalidadContractualID`)
    REFERENCES `modalidadcontractual` (`ID`),
  CONSTRAINT `evento_ibfk_2`
    FOREIGN KEY (`EspacioID`)
    REFERENCES `espacio` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `ModalidadContractualID` ON `evento` (`ModalidadContractualID` ASC) VISIBLE;

CREATE INDEX `EspacioID` ON `evento` (`EspacioID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `responsabilidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `responsabilidad` ;

CREATE TABLE IF NOT EXISTS `responsabilidad` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(255) NOT NULL,
  `Aplica` TINYINT(1) NOT NULL,
  `ModalidadContractualID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `responsabilidad_ibfk_1`
    FOREIGN KEY (`ModalidadContractualID`)
    REFERENCES `modalidadcontractual` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `ModalidadContractualID` ON `responsabilidad` (`ModalidadContractualID` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
