apiVersion: v1
kind: Service
metadata:
  name: aplicativo-capacity-db
  namespace: dev-aplicativo-capacity
spec:
  selector:
    app: aplicativo-capacity-db
  ports:
  - port: 80
    targetPort: 80
    name: http
