# event.py
from tortoise import Model, fields

class Event(Model):
    id = fields.CharField(pk=True, max_length=50)
    event_type = fields.CharField(max_length=100, null=True)
    state = fields.CharField(max_length=50, null=True)
    date_state = fields.DatetimeField(null=True)
    general_name = fields.CharField(max_length=100, null=True)
    specific_name = fields.CharField(max_length=100, null=True)
    date_start = fields.DateField(null=True)
    date_finishing = fields.DateField(null=True)
    hour_start = fields.CharField(max_length=100, null=True)
    hour_finishing = fields.CharField(max_length=100, null=True)
    place = fields.CharField(max_length=100, null=True)
    user_name = fields.CharField(max_length=100, null=True)
    phone = fields.CharField(max_length=50, null=True)
    identification_type = fields.CharField(max_length=50, null=True)
    identification_value = fields.CharField(max_length=50, null=True)
    email = fields.CharField(max_length=100, null=True)
    description = fields.TextField(null=True)
    observation = fields.TextField(null=True)
    duration = fields.CharField(max_length=50, null=True)
    mounting_date = fields.DateField(null=True)
    mounting_start_hour = fields.CharField(max_length=100, null=True)
    mounting_finishing_hour = fields.CharField(max_length=100, null=True)
    technic_contact = fields.CharField(max_length=100, null=True)
    rider =  fields.CharField(max_length=100, null=True)
    min_to_min =  fields.CharField(max_length=100, null=True)
    communication_contact = fields.CharField(max_length=100, null=True)
    pulep = fields.CharField(max_length=50, null=True)
    access_data = fields.TextField(null=True)
    ticket_company = fields.CharField(max_length=100, null=True)
    age_restriction = fields.CharField(max_length=50, null=True)
    agreement = fields.TextField(null=True)
