-- MySQL Script generated by MySQL Workbench
-- Wed Nov 15 16:39:35 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tptu_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tptu_db` ;

-- -----------------------------------------------------
-- Schema tptu_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tptu_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `tptu_db` ;

-- -----------------------------------------------------
-- Table `tptu_db`.`espacios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tptu_db`.`espacios` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tptu_db`.`eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tptu_db`.`eventos` (
  `id` VARCHAR(50) NOT NULL,
  `event_type` VARCHAR(255) NULL DEFAULT NULL,
  `general_name` VARCHAR(255) NULL DEFAULT NULL,
  `specific_name` VARCHAR(255) NULL DEFAULT NULL,
  `date_start` VARCHAR(50) NULL DEFAULT NULL,
  `date_finishing` VARCHAR(50) NULL DEFAULT NULL,
  `hour_start` VARCHAR(50) NULL DEFAULT NULL,
  `hour_finishing` VARCHAR(50) NULL DEFAULT NULL,
  `place` VARCHAR(255) NULL DEFAULT NULL,
  `user_name` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(50) NULL DEFAULT NULL,
  `identification_type` VARCHAR(255) NULL DEFAULT NULL,
  `identification_value` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `observation` TEXT NULL DEFAULT NULL,
  `duration` VARCHAR(30) NULL DEFAULT NULL,
  `mounting_date` VARCHAR(30) NULL DEFAULT NULL,
  `mounting_start_hour` VARCHAR(30) NULL DEFAULT NULL,
  `mounting_finishing_hour` VARCHAR(30) NULL DEFAULT NULL,
  `technic_contact` VARCHAR(255) NULL DEFAULT NULL,
  `rider` VARCHAR(255) NULL DEFAULT NULL,
  `min_tomin` VARCHAR(255) NULL DEFAULT NULL,
  `communication_contact` VARCHAR(255) NULL DEFAULT NULL,
  `pulep` VARCHAR(255) NULL DEFAULT NULL,
  `access_data` TEXT NULL DEFAULT NULL,
  `ticket_company` VARCHAR(255) NULL DEFAULT NULL,
  `age_restriction` VARCHAR(255) NULL DEFAULT NULL,
  `agreement` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tptu_db`.`eventstates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tptu_db`.`eventstates` (
  `id_state` VARCHAR(255) NOT NULL,
  `date_state` VARCHAR(45) NULL DEFAULT NULL,
  `hour_state` VARCHAR(45) NULL DEFAULT NULL,
  `type_state` VARCHAR(45) NULL DEFAULT NULL,
  `justification` TEXT NULL DEFAULT NULL,
  `user_state` VARCHAR(45) NULL DEFAULT NULL,
  `event_id` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_state`),
  CONSTRAINT `event_state`
    FOREIGN KEY (`event_id`)
    REFERENCES `tptu_db`.`eventos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `event_state_idx` ON `tptu_db`.`eventstates` (`event_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tptu_db`.`historyeventstates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tptu_db`.`historyeventstates` (
  `id_history` INT NOT NULL AUTO_INCREMENT,
  `date_state` VARCHAR(45) NULL DEFAULT NULL,
  `hour_state` VARCHAR(45) NULL DEFAULT NULL,
  `type_state` VARCHAR(45) NULL DEFAULT NULL,
  `justification` TEXT NULL DEFAULT NULL,
  `user_state` VARCHAR(255) NULL DEFAULT NULL,
  `eventstate_id` VARCHAR(60) NULL DEFAULT NULL,
  PRIMARY KEY (`id_history`),
  CONSTRAINT `history_eventstate`
    FOREIGN KEY (`eventstate_id`)
    REFERENCES `tptu_db`.`eventstates` (`id_state`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `history_eventstate_idx` ON `tptu_db`.`historyeventstates` (`eventstate_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tptu_db`.`sub_eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tptu_db`.`sub_eventos` (
  `id` VARCHAR(50) NOT NULL,
  `event_type` VARCHAR(255) NULL DEFAULT NULL,
  `event_id` VARCHAR(255) NULL DEFAULT NULL,
  `general_name` VARCHAR(255) NULL DEFAULT NULL,
  `specific_name` VARCHAR(255) NULL DEFAULT NULL,
  `date_start` VARCHAR(30) NULL DEFAULT NULL,
  `date_finishing` VARCHAR(30) NULL DEFAULT NULL,
  `hour_start` VARCHAR(30) NULL DEFAULT NULL,
  `hour_finishing` VARCHAR(30) NULL DEFAULT NULL,
  `place` VARCHAR(255) NULL DEFAULT NULL,
  `user_name` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(50) NULL DEFAULT NULL,
  `identification_type` VARCHAR(255) NULL DEFAULT NULL,
  `identification_value` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `observation` TEXT NULL DEFAULT NULL,
  `duration` VARCHAR(50) NULL DEFAULT NULL,
  `mounting_date` VARCHAR(30) NULL DEFAULT NULL,
  `mounting_start_hour` VARCHAR(30) NULL DEFAULT NULL,
  `mounting_finishing_hour` VARCHAR(30) NULL DEFAULT NULL,
  `technic_contact` VARCHAR(255) NULL DEFAULT NULL,
  `rider` VARCHAR(255) NULL DEFAULT NULL,
  `min_tomin` VARCHAR(255) NULL DEFAULT NULL,
  `communication_contact` VARCHAR(255) NULL DEFAULT NULL,
  `pulep` VARCHAR(255) NULL DEFAULT NULL,
  `access_data` TEXT NULL DEFAULT NULL,
  `ticket_company` VARCHAR(255) NULL DEFAULT NULL,
  `age_restriction` VARCHAR(255) NULL DEFAULT NULL,
  `agreement` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `event_subevent`
    FOREIGN KEY (`event_id`)
    REFERENCES `tptu_db`.`eventos` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `event_subevent_idx` ON `tptu_db`.`sub_eventos` (`event_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tptu_db`.`subeventstates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tptu_db`.`subeventstates` (
  `id_state` VARCHAR(255) NOT NULL,
  `date_state` VARCHAR(45) NULL DEFAULT NULL,
  `hour_state` VARCHAR(45) NULL DEFAULT NULL,
  `type_state` VARCHAR(105) NULL DEFAULT NULL,
  `justification` TEXT NULL DEFAULT NULL,
  `user_state` VARCHAR(255) NULL DEFAULT NULL,
  `subevent_id` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_state`),
  CONSTRAINT `subevent_state`
    FOREIGN KEY (`subevent_id`)
    REFERENCES `tptu_db`.`sub_eventos` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `subevent_state_idx` ON `tptu_db`.`subeventstates` (`subevent_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tptu_db`.`historysubeventstates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tptu_db`.`historysubeventstates` (
  `id_history` INT NOT NULL AUTO_INCREMENT,
  `date_state` VARCHAR(45) NULL DEFAULT NULL,
  `hour_state` VARCHAR(45) NULL DEFAULT NULL,
  `type_state` VARCHAR(45) NULL DEFAULT NULL,
  `justification` TEXT NULL DEFAULT NULL,
  `user_state` VARCHAR(255) NULL DEFAULT NULL,
  `subeventstate_id` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_history`),
  CONSTRAINT `history_subevent`
    FOREIGN KEY (`subeventstate_id`)
    REFERENCES `tptu_db`.`subeventstates` (`id_state`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `history_subevent_idx` ON `tptu_db`.`historysubeventstates` (`subeventstate_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tptu_db`.`modalidadescontractuales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tptu_db`.`modalidadescontractuales` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tptu_db`.`responsabilidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tptu_db`.`responsabilidades` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(255) NULL DEFAULT NULL,
  `Descripcion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tptu_db`.`responsabilidadespormodalidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tptu_db`.`responsabilidadespormodalidades` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Aplica` TINYINT(1) NULL DEFAULT NULL,
  `Responsabilidad_ID` INT NULL DEFAULT NULL,
  `Modalidad_ID` INT NULL DEFAULT NULL,
  `Espacio_ID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `responsabilidadespormodalidades_ibfk_1`
    FOREIGN KEY (`Responsabilidad_ID`)
    REFERENCES `tptu_db`.`responsabilidades` (`ID`),
  CONSTRAINT `responsabilidadespormodalidades_ibfk_2`
    FOREIGN KEY (`Modalidad_ID`)
    REFERENCES `tptu_db`.`modalidadescontractuales` (`ID`),
  CONSTRAINT `responsabilidadespormodalidades_ibfk_3`
    FOREIGN KEY (`Espacio_ID`)
    REFERENCES `tptu_db`.`espacios` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `Responsabilidad_ID` ON `tptu_db`.`responsabilidadespormodalidades` (`Responsabilidad_ID` ASC) VISIBLE;

CREATE INDEX `Modalidad_ID` ON `tptu_db`.`responsabilidadespormodalidades` (`Modalidad_ID` ASC) VISIBLE;

CREATE INDEX `Espacio_ID` ON `tptu_db`.`responsabilidadespormodalidades` (`Espacio_ID` ASC) INVISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
