apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: aplicativo-capacity-db
  namespace: dev-aplicativo-capacity
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aplicativo-capacity-db
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 60
